default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: twitter_development

test:
  <<: *default
  database: twitter_test

production:
  <<: *default
  database: twitter_production
